namespace: ci-ska-mid-cbf-system-tests-1451523941-jkwso
subarray: 1
vcc_boards: [1]                # boards receiving data
fsp_boards: [1]                # boards running FSP
fs_slices: [1]                 # frequency slices to process for each FSP. The length of list must match fsp_boards.
fsp_cfg: default                     # must match a key in configure_scan.json
download_artifacts: True            # True to download artifacts from CAR and populate the DB with HPS devices
hw_config: hw_config_swap_psi.yaml        # must match one of the files in the hw_config directory
dish_vcc_config: psi.yaml       # must match one of the files in the dish_vcc_mapping directory
generate_lstv: True                  # set to True to generate LSTV. Can be set to False if re-running tests without
                                     # turning boards off in between.
vis_capture_image: artefact.skao.int/ska-mid-cbf-signal-verification-visibility-capture:0.2.24
vis_capture_port: 14000              # port number to start capturing from. Each freq slice takes 744 ports starting from this.
run_tcpdump: False                   # runs tcpdump to save packets sent to SDP in a pcap file instead of the capture.py
result_dir: ./result/