apiVersion: v1
kind: Pod
metadata:
  name: cloud03-sdn-dynamic-vis
  annotations:
    k8s.v1.cni.cncf.io/networks: kube-system/sdn
spec:
  containers:
    - name: cloud03-sdn-dynamic-vis
      image: artefact.skao.int/ska-mid-cbf-signal-verification-visibility-capture:0.2.16
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-c"]
      args:
        ["apt update && apt install -y tcpdump iproute2 && tail -f /dev/null"]

